### ISSUE TITLE
Asset version tags are not populated

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#17]
In admin pages source some assets have {{version}} tags, e.g.
`<link rel="stylesheet" href="http://localhost/postleaf/source/assets/css/lib.css?v={{version}}">`

**Comment by claviska** [comment]
Thanks, last minute changed caused this oversight. I've fixed that and another related issue where I was using `{{version}}` instead of `{{@postleaf.version}}`. 👍

**Comment by joshas** [comment]
I'm still getting this issue in latest beta-6. Was POSTLEAF_VERSION left set to {{version}} intentionally?

**Comment by claviska** [comment]
Not intentional. Some of the helpers were still using the constant. Fixed now.
