### ISSUE TITLE
Postleaf failed to start! SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by lukewatts** [Postleaf/postleaf#22]
### Summary

I've followed the article here for Ubuntu:16.04

[https://www.postleaf.org/installing-postleaf-on-digitalocean?v=1](https://www.postleaf.org/installing-postleaf-on-digitalocean?v=1)

But when I run `node app.js` I get the following error:

```
Error: Postleaf failed to start!

SequelizeUniqueConstraintError: Validation error
```

Not sure where to go from here. Any suggestions what this error means?

### Steps to Reproduce

1. Install git nginx sqlite3 nodejs (7) and graphicsmagick
2. Clone repo into /var/www/postleaf
3.Clone Empower theme into theme directory
4. Globally install npm-gyp npm-pre-gyp sqlite3 and sequelize (`sudo npm install -g npm-gyp npm-pre-gyp sqlite3 sequelize gulp`)
5. Rebuild the following packages - node-gyp node-sass optipng-bin jpegtran-bin sqlite3 sequelize
6. Run `npm install`
7. Run `gulp build`
8. Run `node app.js`

### Additional info

- Postleaf version: master
- Node version: 7.9.0
- Affected browsers: N/A
- Operating system: Ubuntu:16.04

**Comment by claviska** [comment]
Are you using the code from [1.0.0-alpha.1](https://github.com/Postleaf/postleaf/releases/tag/1.0.0-alpha.1) or master?

I just released [1.0.0-alpha.2](https://github.com/Postleaf/postleaf/releases/tag/1.0.0-alpha.2) so I'd recommend using that instead. It has a number of bug fixes, including #9 which should resolve the issue you're having.

If not, comment here and I'll reopen. But I'm pretty sure that will fix it. 😎

**Comment by lukewatts** [comment]
I'm still getting that error. Which branch are you developing on and which is the stable? The tagged version 1.0.0-alpha.2 still gives me this error.

**Comment by claviska** [comment]
Dev is on master. If you create the `data` directory manually, does that resolve it? If so, it's likely a permissions issue. Try checking the owner and permissions.

**Comment by claviska** [comment]
Going to try a daring live stream of the DigitalOcean tutorial in a sec: https://www.twitch.tv/claviska

**Comment by lukewatts** [comment]
So I did a `chown -R $USER:www-data .` AFTER I ran `npm install` and `gulp build` and that fixed that error.

But now I'm getting a few 404 errors on the login page for assets.

**Comment by claviska** [comment]
Were you logged in as root or as the non-root user? Not sure why that would happen if you ran `npm install && gulp build` as non-root.

**Comment by lukewatts** [comment]
I'm not sure either...but running setting the permissions just before `node app.js` sorted it.

**Comment by venatoria** [comment]
@lukewatts I will test myself and see if that solves it. 
Akmost sure it's a permission issue indeed

**Comment by claviska** [comment]
Resolved with 48eb7c4.
